import { NgModule } from "@angular/core";
import { PolymorpheusModule } from "@tinkoff/ng-polymorpheus";
import {
  TuiActiveZoneModule,
  TuiAutoFocusModule,
  TuiDialogHostModule,
  TuiDropdownHostModule,
  TuiFilterPipeModule,
  TuiLetModule,
} from "@taiga-ui/cdk";
import {
  TuiButtonModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiDropdownModule,
  TuiFlagPipeModule,
  TuiFormatNumberPipeModule,
  TuiGroupModule,
  TuiHintModule,
  TuiHostedDropdownModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiNotificationModule,
  TuiPrimitiveTextfieldModule,
  TuiScrollbarModule,
  TuiTextfieldControllerModule,
  TuiTooltipModule,
} from "@taiga-ui/core";

import { TuiSheetDialogModule, TuiTabBarModule } from "@taiga-ui/addon-mobile";
import {
  TuiAccordionModule,
  TuiActionModule,
  TuiArrowModule,
  TuiAvatarModule,
  TuiBadgeModule,
  TuiBadgedContentModule,
  TuiBreadcrumbsModule,
  TuiCheckboxLabeledModule,
  TuiComboBoxModule,
  TuiDataListWrapperModule,
  TuiFilterByInputPipeModule,
  TuiInputFilesModule,
  TuiInputModule,
  TuiInputNumberModule,
  TuiInputPhoneInternationalModule,
  TuiInputPhoneModule,
  TuiIslandModule,
  TuiLineClampModule,
  TuiMarkerIconModule,
  TuiMultiSelectModule,
  TuiProgressModule,
  TuiRadioBlockModule,
  TuiRadioGroupModule,
  TuiRadioModule,
  TuiRatingModule,
  TuiSelectModule,
  TuiStringifyContentPipeModule,
  TuiStringifyPipeModule,
  TuiTagModule,
  TuiTextareaModule,
  TuiToggleModule,
} from "@taiga-ui/kit";
import { TuiPreviewModule } from "@taiga-ui/addon-preview";
import { TuiInputDateModule } from "@taiga-ui/kit";
import { TuiTableModule } from "@taiga-ui/addon-table";
import { TuiBlockStatusModule } from "@taiga-ui/layout";

const IMPORTS = [
  TuiSelectModule,
  TuiDataListModule,
  TuiDataListWrapperModule,
  TuiActiveZoneModule,
  TuiDropdownModule,
  TuiHostedDropdownModule,
  TuiButtonModule,
  TuiInputModule,
  TuiLabelModule,
  TuiTextfieldControllerModule,
  TuiBadgedContentModule,
  TuiBadgeModule,
  TuiTabBarModule,
  TuiArrowModule,
  TuiIslandModule,
  TuiLineClampModule,
  TuiAvatarModule,
  TuiActionModule,
  TuiPreviewModule,
  TuiDialogModule,
  TuiScrollbarModule,
  TuiInputPhoneModule,
  TuiInputPhoneInternationalModule,
  TuiPrimitiveTextfieldModule,
  TuiBreadcrumbsModule,
  TuiProgressModule,
  TuiLabelModule,
  TuiTextareaModule,
  TuiInputNumberModule,
  TuiNotificationModule,
  TuiRatingModule,
  TuiTooltipModule,
  TuiHintModule,
  TuiSheetDialogModule,
  TuiDialogHostModule,
  TuiDropdownHostModule,
  TuiInputDateModule,
  TuiTableModule,
  TuiTagModule,
  TuiLetModule,
  TuiBlockStatusModule,
  TuiInputFilesModule,
  TuiMarkerIconModule,
  TuiGroupModule,
  TuiRadioGroupModule,
  TuiRadioModule,
  TuiRadioBlockModule,
  TuiAccordionModule,
  TuiToggleModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiComboBoxModule,
  TuiMultiSelectModule,
  TuiFlagPipeModule,
  TuiAutoFocusModule,
  TuiCheckboxLabeledModule,
  PolymorpheusModule,
  TuiStringifyPipeModule,
  TuiFilterPipeModule,
  TuiFilterByInputPipeModule,
  TuiStringifyContentPipeModule,
  TuiFormatNumberPipeModule,
];

@NgModule({
  imports: [...IMPORTS],
  exports: [...IMPORTS],
  declarations: [],
  providers: [],
})
export class TaigaUIModule {}
